"use client";

import { Inter } from "next/font/google";
// import "./globals.css";
import "./custom.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { useContext, useState } from "react";
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
import { SearchContext } from "./store/search-context";
export default function RootLayout({ children }) {
  const [search, setSearch] = useState("series");

  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="https://w7.pngwing.com/pngs/153/31/png-transparent-netflix-macos-bigsur-icon-thumbnail.png"
        />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css"
        />
      </head>
      <body className="bg-netflix mx-5">
        <SearchContext.Provider value={search}>
          <Header setSearch={setSearch} />
          {children}
          <Footer />
        </SearchContext.Provider>
      </body>
    </html>
  );
}
