"use client";

import { Inter } from "next/font/google";
// import "./globals.css";
import "./custom.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { useState } from "react";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [search, setSearch] = useState("series");
  return (
    <html lang="en">
      <body className="bg-netflix mx-5">
        <Header setSearch={setSearch} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
